variables:
  DEBIAN_FRONTEND: noninteractive
  APT_GET_INSTALL: "apt-get install --no-install-recommends -q -y"

stages:
  - check_coding_style
  - test_build
  - release
  - deploy

.display_env:
  before_script:
    - date
    - uname -a
    - cat /etc/os-release

pre-commit:
  stage: check_coding_style
  image:
    # https://hub.docker.com/_/alpine
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache git npm pre-commit
    - pre-commit --version
    - pre-commit run --all-files --show-diff-on-failure
    - pre-commit autoupdate --jobs $((($(nproc) * 3 + 2 - 1)/2))
    - git diff .pre-commit-config.yaml

cppcheck:
  stage: check_coding_style
  image:
    # https://hub.docker.com/_/alpine
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache cppcheck
    - find . \( -iname "*.ino" -o -iname "*.c++" -o -iname "*.h" \) -print0 | xargs -0 cppcheck --suppress="*:test/*" --suppress=missingIncludeSystem --suppress=missingInclude --enable=warning,performance,portability,information --error-exitcode=1 --check-level=exhaustive

arduino-lint:
  stage: check_coding_style
  image:
    # https://hub.docker.com/_/debian
    name: debian:latest
  extends: .display_env
  script:
    - apt-get update
    - $APT_GET_INSTALL curl ca-certificates
    - (cd && curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh)
    - ~/bin/arduino-lint --version
    - ~/bin/arduino-lint --compliance strict --library-manager update

arduino_ci:
  stage: test_build
  image:
    # https://hub.docker.com/_/debian
    name: debian:latest
  extends: .display_env
  script:
    - apt-get update
    - $APT_GET_INSTALL ruby build-essential
    - gem install bundler arduino_ci
    - export EXPECT_UNITTESTS=1
    - export EXPECT_EXAMPLES=1
    - arduino_ci.rb

prepare_release:
  stage: test_build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    # https://hub.docker.com/_/alpine
    name: alpine:latest
  extends: .display_env
  script:
    - cat library.properties
    - echo "EXTRA_DESCRIPTION=$(grep sentence library.properties | cut -d "=" -f 2) $(grep paragraph library.properties | cut -d '=' -f 2)" > variables.env
    - echo "TAG=$(grep version library.properties | cut -d "=" -f 2)" >> variables.env
    - cat variables.env
  artifacts:
    expire_in: 1 hrs
    reports:
      dotenv: variables.env

release_job:
  stage: release
  image:
    # https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-release-metadata-in-a-custom-script
    registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: arduino-lint
    - job: arduino_ci
    - job: prepare_release
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - date
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    description: '$EXTRA_DESCRIPTION'
    tag_name: '$TAG'
    ref: '$CI_COMMIT_SHA'

trigger_deploy2zenodo:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_SERVER_HOST == "gitlab.com"
  variables:
    TAG: $TAG
    TAG_COMMIT_SHA: $CI_COMMIT_SHA
    TAG_COMMIT_TIMESTAMP: $CI_COMMIT_TIMESTAMP
  trigger:
    project: daniel_mohr/deploy_fast_samd21_tc_to_zenodo
    strategy: depend
    forward:
      yaml_variables: true
      pipeline_variables: false
